--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.DICT_SMOKE_TEST_PARAMETERS contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
  CREATE TABLE "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" (
    "CORRELATION_ID" VARCHAR2(128 CHAR), 
    "ID_CUID" NUMBER, 
    "CHANNEL_CD" VARCHAR2(3 CHAR), 
    "PHONE_NUMBER" VARCHAR2(250 CHAR), 
    "HOSTNAME" VARCHAR2(50 CHAR), 
    "FLAG_ACTIVE" VARCHAR2(1 CHAR),  
    ENVIRONMENT  VARCHAR2(10 CHAR)
) 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO RTDM_TEMP
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO HCI_RO_INT_COMMUNICATION
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO MA_TEMP
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO SAS_INT_COMM_DICT_RW
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO SAS_INT_COMM_RW
/
GRANT SELECT ON "INT_COMMUNICATION"."DICT_SMOKE_TEST_PARAMETERS" TO SAS_INT_COMMUNICATION_RO
/